#!/usr/bin/env python3

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mo2ctl


class Mo2CtlCheckpointTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name) / "mo2"
        self.profile = self.root / "profiles" / "QA"
        (self.root / "mods").mkdir(parents=True)
        self.profile.mkdir(parents=True)
        (self.profile / "modlist.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n"
            b"-Known Mod\r\n"
        )
        (self.profile / "plugins.txt").write_text(
            "# This file was automatically generated by Mod Organizer.\n",
            encoding="utf-8",
        )
        (self.profile / "loadorder.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n"
        )
        (self.profile / "archives.txt").write_bytes(b"Skyrim - Misc.bsa\r\n")
        self.env = mo2ctl.Env(self.root, "QA")
        self._lock = mo2ctl.profile_lock_reason
        mo2ctl.profile_lock_reason = lambda: None

    def tearDown(self) -> None:
        mo2ctl.profile_lock_reason = self._lock
        self.tmp.cleanup()

    @property
    def manifest_path(self) -> Path:
        return self.root / "profiles" / "manifest.json"

    @property
    def state_path(self) -> Path:
        return self.root / "profiles" / "profile-state.json"

    def invoke(self, *argv: str) -> dict:
        args = mo2ctl.build_parser().parse_args(list(argv))
        return args.func(self.env, args)

    def write_manifest(self, mods: dict[str, dict]) -> None:
        self.manifest_path.write_text(
            json.dumps(
                {"format": mo2ctl.PROFILE_MANIFEST_FORMAT, "mods": mods},
                indent=1,
                ensure_ascii=False,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )

    def read_manifest(self) -> dict:
        return json.loads(self.manifest_path.read_text(encoding="utf-8"))

    def read_state(self) -> dict:
        return json.loads(self.state_path.read_text(encoding="utf-8"))

    def write_reconcile_fixture(self) -> None:
        (self.profile / "modlist.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n"
            b"+A\r\n+B\r\n+C\r\n-D\r\n"
        )
        self.write_manifest(
            {
                "A": {"enabled": False, "source_path": "/archives/A.zip"},
                "D": {"enabled": False, "source_path": "/archives/D.zip"},
                "Stale": {"enabled": True, "source_path": "/archives/Stale.zip"},
            }
        )

    def test_enable_syncs_manifest_and_writes_checkpoint(self) -> None:
        self.write_manifest({"Known Mod": {"enabled": False}})

        self.invoke("enable", "Known Mod")

        manifest = self.read_manifest()
        state = self.read_state()
        self.assertIs(manifest["mods"]["Known Mod"]["enabled"], True)
        self.assertEqual(manifest["updated_by"], "mo2ctl:enable")
        self.assertEqual(state["source"], "mo2ctl:enable")
        self.assertIn("Known Mod", state["enabled"])

    def test_disable_syncs_manifest_and_writes_checkpoint(self) -> None:
        (self.profile / "modlist.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n"
            b"+Known Mod\r\n"
        )
        self.write_manifest({"Known Mod": {"enabled": True}})

        self.invoke("disable", "Known Mod")

        manifest = self.read_manifest()
        state = self.read_state()
        self.assertIs(manifest["mods"]["Known Mod"]["enabled"], False)
        self.assertEqual(manifest["updated_by"], "mo2ctl:disable")
        self.assertEqual(state["source"], "mo2ctl:disable")
        self.assertNotIn("Known Mod", state["enabled"])

    def test_install_no_manifest_marks_checkpoint_dirty_without_new_entry(self) -> None:
        self.write_manifest({"Known Mod": {"enabled": False}})
        plugin = Path(self.tmp.name) / "NoManifest.esp"
        plugin.write_bytes(b"")

        self.invoke("install", str(plugin), "--name", "No Manifest", "--no-manifest")

        self.assertNotIn("No Manifest", self.read_manifest()["mods"])
        self.assertEqual(self.read_state()["manifest_dirty"], "--no-manifest")

    def test_reconcile_dry_run_reports_diff_without_writing(self) -> None:
        self.write_reconcile_fixture()
        manifest_before = self.manifest_path.read_bytes()

        result = self.invoke("reconcile")

        self.assertEqual(
            {key: result[key] for key in (
                "modlist_enabled",
                "manifest_mods",
                "only_in_modlist",
                "only_in_manifest",
                "enabled_mismatch",
            )},
            {
                "modlist_enabled": 3,
                "manifest_mods": 3,
                "only_in_modlist": 2,
                "only_in_manifest": 1,
                "enabled_mismatch": 1,
            },
        )
        self.assertIs(result["applied"], False)
        self.assertEqual(self.manifest_path.read_bytes(), manifest_before)
        self.assertFalse(self.state_path.exists())

    def test_reconcile_apply_syncs_only_existing_entries(self) -> None:
        self.write_reconcile_fixture()
        entry_count = len(self.read_manifest()["mods"])

        result = self.invoke("reconcile", "--apply")

        manifest = self.read_manifest()
        state = self.read_state()
        self.assertIs(result["applied"], True)
        self.assertEqual(result["enabled_mismatch"], 0)
        self.assertEqual(len(manifest["mods"]), entry_count)
        self.assertEqual(manifest["updated_by"], "reconcile:external")
        self.assertEqual(len(state["unregistered"]), 2)
        self.assertEqual(len(state["stale"]), 1)

    def test_reconcile_detects_external_write_and_can_fail_on_drift(self) -> None:
        self.write_manifest({"Known Mod": {"enabled": False}})
        self.invoke("enable", "Known Mod")
        modlist = self.profile / "modlist.txt"
        modlist.write_bytes(modlist.read_bytes().replace(b"+Known Mod", b"-Known Mod"))

        result = self.invoke("reconcile")

        self.assertIs(result["external_write_detected"], True)
        self.assertEqual(result["changed_files"], ["modlist"])
        with self.assertRaises(mo2ctl.Fail):
            self.invoke("reconcile", "--fail-on-drift")


if __name__ == "__main__":
    unittest.main()
