#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mo2ctl


class Mo2CtlArchiveTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name) / "mo2"
        self.profile = self.root / "profiles" / "QA"
        (self.root / "mods").mkdir(parents=True)
        self.profile.mkdir(parents=True)
        (self.profile / "modlist.txt").write_bytes(b"# This file was automatically generated by Mod Organizer.\r\n+Core Mod\r\n-Old Mod\r\n")
        (self.profile / "plugins.txt").write_text("# This file was automatically generated by Mod Organizer.\n", encoding="utf-8")
        (self.profile / "loadorder.txt").write_bytes(b"# This file was automatically generated by Mod Organizer.\r\n")
        (self.profile / "archives.txt").write_bytes(b"Skyrim - Misc.bsa\r\n")
        self.env = mo2ctl.Env(self.root, "QA")
        self._lock = mo2ctl.profile_lock_reason
        mo2ctl.profile_lock_reason = lambda: None

    def tearDown(self) -> None:
        mo2ctl.profile_lock_reason = self._lock
        self.tmp.cleanup()

    def args(self, source: Path, **overrides) -> argparse.Namespace:
        data = {
            "source": str(source),
            "name": overrides.pop("name", None),
            "no_enable": overrides.pop("no_enable", False),
            "force": overrides.pop("force", False),
            "priority": overrides.pop("priority", "bottom"),
            "fomod_choices": overrides.pop("fomod_choices", None),
            "version": overrides.pop("version", "0.0.0"),
            "comment": overrides.pop("comment", "test"),
        }
        data.update(overrides)
        return argparse.Namespace(**data)

    def zipfile(self, name: str, entries: dict[str, str]) -> Path:
        path = Path(self.tmp.name) / name
        with zipfile.ZipFile(path, "w") as zf:
            for member, text in entries.items():
                zf.writestr(member, text)
        return path

    def test_zip_install_defaults_to_bottom_and_updates_unmanaged_bsa(self) -> None:
        archive = self.zipfile("ThirdParty.zip", {
            "Wrapper/Data/TestPlugin.esp": "",
            "Wrapper/Data/Test Assets.bsa": "",
        })

        result = mo2ctl.cmd_install(self.env, self.args(archive, name="ThirdParty"))

        self.assertEqual(result["priority"], "bottom")
        self.assertEqual(result["plugins_activated"], ["TestPlugin.esp"])
        self.assertEqual(result["archives_added"], ["Test Assets.bsa"])
        self.assertTrue((self.root / "mods" / "ThirdParty" / "TestPlugin.esp").is_file())
        modlist = (self.profile / "modlist.txt").read_bytes()
        self.assertTrue(modlist.endswith(b"-Old Mod\r\n+ThirdParty\r\n"))
        self.assertIn("*TestPlugin.esp", (self.profile / "plugins.txt").read_text(encoding="utf-8"))
        self.assertIn("Test Assets.bsa", (self.profile / "archives.txt").read_text(encoding="utf-8"))

    def test_matching_plugin_bsa_is_not_added_to_archives(self) -> None:
        archive = self.zipfile("ManagedBsa.zip", {
            "Data/TestPlugin.esp": "",
            "Data/TestPlugin.bsa": "",
        })

        result = mo2ctl.cmd_install(self.env, self.args(archive, name="ManagedBsa"))

        self.assertEqual(result["archives_found"], ["TestPlugin.bsa"])
        self.assertEqual(result["archives_added"], [])
        self.assertNotIn("TestPlugin.bsa", (self.profile / "archives.txt").read_text(encoding="utf-8"))

    def test_priority_after_anchor(self) -> None:
        archive = self.zipfile("Anchored.zip", {"Data/Anchored.esp": ""})

        mo2ctl.cmd_install(self.env, self.args(archive, name="Anchored", priority="after:Core Mod"))

        self.assertEqual(
            (self.profile / "modlist.txt").read_bytes().splitlines(),
            [
                b"# This file was automatically generated by Mod Organizer.",
                b"+Core Mod",
                b"+Anchored",
                b"-Old Mod",
            ],
        )

    def test_fomod_materializes_replayable_default_choices(self) -> None:
        archive = self.zipfile("Fomod.zip", {
            "fomod/info.xml": "<fomod><Name>Fomod Name</Name><Version>1.2.3</Version></fomod>",
            "fomod/ModuleConfig.xml": """
                <config>
                  <requiredInstallFiles>
                    <folder source="00 Core" destination="" />
                  </requiredInstallFiles>
                  <installSteps>
                    <installStep name="Options">
                      <optionalFileGroups>
                        <group name="Textures" type="SelectAny">
                          <plugins>
                            <plugin name="2K">
                              <typeDescriptor><type name="Required" /></typeDescriptor>
                              <files><folder source="10 2K/textures" destination="textures" /></files>
                            </plugin>
                          </plugins>
                        </group>
                      </optionalFileGroups>
                    </installStep>
                  </installSteps>
                </config>
            """,
            "00 Core/Fomod.esp": "",
            "10 2K/textures/example.dds": "dds",
        })

        inspected = mo2ctl.inspect_source(archive)
        self.assertEqual(inspected["fomod"]["default_choices"]["status"], "ready")
        result = mo2ctl.cmd_install(self.env, self.args(archive))

        dest = self.root / "mods" / "Fomod Name"
        self.assertEqual(result["installed"], "Fomod Name")
        self.assertTrue((dest / "Fomod.esp").is_file())
        self.assertTrue((dest / "textures" / "example.dds").is_file())
        self.assertEqual(
            json.loads((dest / "mo2ctl-fomod-choices.json").read_text(encoding="utf-8"))["status"],
            "ready",
        )
        self.assertIn("version=1.2.3", (dest / "meta.ini").read_text(encoding="utf-8"))

    def test_zip_slip_is_rejected(self) -> None:
        archive = self.zipfile("Bad.zip", {"../evil.esp": ""})

        with self.assertRaisesRegex(mo2ctl.Fail, "unsafe archive path"):
            mo2ctl.inspect_source(archive)

    def test_absolute_archive_path_is_rejected(self) -> None:
        archive = self.zipfile("Absolute.zip", {"/evil.esp": ""})

        with self.assertRaisesRegex(mo2ctl.Fail, "unsafe archive path"):
            mo2ctl.inspect_source(archive)

    def test_fomod_root_wins_over_data_child(self) -> None:
        archive = self.zipfile("FomodData.zip", {
            "fomod/ModuleConfig.xml": "<config />",
            "Data/ShouldNotHideFomod.esp": "",
        })

        inspected = mo2ctl.inspect_source(archive)

        self.assertTrue(inspected["has_fomod"])

    def test_unsupported_conditional_fomod_handoffs(self) -> None:
        archive = self.zipfile("Conditional.zip", {
            "fomod/ModuleConfig.xml": """
                <config>
                  <conditionalFileInstalls>
                    <patterns><pattern><dependencies /></pattern></patterns>
                  </conditionalFileInstalls>
                </config>
            """,
        })

        with self.assertRaisesRegex(mo2ctl.Fail, "handoff_user"):
            mo2ctl.cmd_install(self.env, self.args(archive))

    def test_at_least_one_without_default_handoffs(self) -> None:
        archive = self.zipfile("PickOne.zip", {
            "fomod/ModuleConfig.xml": """
                <config>
                  <installSteps>
                    <installStep name="Files">
                      <optionalFileGroups>
                        <group name="Plugin" type="SelectAtLeastOne">
                          <plugins>
                            <plugin name="DLL"><files><folder source="SKSE" destination="SKSE" /></files></plugin>
                          </plugins>
                        </group>
                      </optionalFileGroups>
                    </installStep>
                  </installSteps>
                </config>
            """,
            "SKSE/Plugins/example.dll": "",
        })

        inspected = mo2ctl.inspect_source(archive)

        self.assertEqual(inspected["fomod"]["default_choices"]["status"], "handoff_user")
        self.assertIn("SelectAtLeastOne", inspected["fomod"]["default_choices"]["handoff_reasons"][0])


if __name__ == "__main__":
    unittest.main()
