#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import unittest
import zipfile
from datetime import timedelta, timezone
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mo2ctl


class Mo2CtlArchiveTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name) / "mo2"
        self.profile = self.root / "profiles" / "QA"
        (self.root / "mods").mkdir(parents=True)
        self.profile.mkdir(parents=True)
        (self.profile / "modlist.txt").write_bytes(b"# This file was automatically generated by Mod Organizer.\r\n+Core Mod\r\n-Old Mod\r\n")
        (self.profile / "plugins.txt").write_text("# This file was automatically generated by Mod Organizer.\n", encoding="utf-8")
        (self.profile / "loadorder.txt").write_bytes(b"# This file was automatically generated by Mod Organizer.\r\n")
        (self.profile / "archives.txt").write_bytes(b"Skyrim - Misc.bsa\r\n")
        self.env = mo2ctl.Env(self.root, "QA")
        self._lock = mo2ctl.profile_lock_reason
        mo2ctl.profile_lock_reason = lambda: None

    def tearDown(self) -> None:
        mo2ctl.profile_lock_reason = self._lock
        self.tmp.cleanup()

    def args(self, source: Path, **overrides) -> argparse.Namespace:
        data = {
            "source": str(source),
            "name": overrides.pop("name", None),
            "no_enable": overrides.pop("no_enable", False),
            "force": overrides.pop("force", False),
            "priority": overrides.pop("priority", "bottom"),
            "fomod_choices": overrides.pop("fomod_choices", None),
            "version": overrides.pop("version", "0.0.0"),
            "source_url": overrides.pop("source_url", None),
            "no_manifest": overrides.pop("no_manifest", False),
            "comment": overrides.pop("comment", "test"),
        }
        data.update(overrides)
        return argparse.Namespace(**data)

    def zipfile(self, name: str, entries: dict[str, str]) -> Path:
        path = Path(self.tmp.name) / name
        with zipfile.ZipFile(path, "w") as zf:
            for member, text in entries.items():
                zf.writestr(member, text)
        return path

    def test_zip_install_defaults_to_bottom_and_updates_unmanaged_bsa(self) -> None:
        archive = self.zipfile("ThirdParty.zip", {
            "Wrapper/Data/TestPlugin.esp": "",
            "Wrapper/Data/Test Assets.bsa": "",
        })

        result = mo2ctl.cmd_install(self.env, self.args(archive, name="ThirdParty"))

        self.assertEqual(result["priority"], "bottom")
        self.assertEqual(result["plugins_activated"], ["TestPlugin.esp"])
        self.assertEqual(result["archives_added"], ["Test Assets.bsa"])
        self.assertTrue((self.root / "mods" / "ThirdParty" / "TestPlugin.esp").is_file())
        modlist = (self.profile / "modlist.txt").read_bytes()
        self.assertTrue(modlist.endswith(b"-Old Mod\r\n+ThirdParty\r\n"))
        self.assertIn("*TestPlugin.esp", (self.profile / "plugins.txt").read_text(encoding="utf-8"))
        self.assertIn("Test Assets.bsa", (self.profile / "archives.txt").read_text(encoding="utf-8"))
        manifest = json.loads((self.root / "profiles" / "manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["format"], mo2ctl.PROFILE_MANIFEST_FORMAT)
        self.assertEqual(manifest["mods"]["ThirdParty"]["plugins"], ["TestPlugin.esp"])
        self.assertEqual(manifest["mods"]["ThirdParty"]["archives"], ["Test Assets.bsa"])

    def test_matching_plugin_bsa_is_not_added_to_archives(self) -> None:
        archive = self.zipfile("ManagedBsa.zip", {
            "Data/TestPlugin.esp": "",
            "Data/TestPlugin.bsa": "",
        })

        result = mo2ctl.cmd_install(self.env, self.args(archive, name="ManagedBsa"))

        self.assertEqual(result["archives_found"], ["TestPlugin.bsa"])
        self.assertEqual(result["archives_added"], [])
        self.assertNotIn("TestPlugin.bsa", (self.profile / "archives.txt").read_text(encoding="utf-8"))

    def test_priority_after_anchor(self) -> None:
        archive = self.zipfile("Anchored.zip", {"Data/Anchored.esp": ""})

        mo2ctl.cmd_install(self.env, self.args(archive, name="Anchored", priority="after:Core Mod"))

        self.assertEqual(
            (self.profile / "modlist.txt").read_bytes().splitlines(),
            [
                b"# This file was automatically generated by Mod Organizer.",
                b"+Core Mod",
                b"+Anchored",
                b"-Old Mod",
            ],
        )

    def test_fomod_materializes_replayable_default_choices(self) -> None:
        archive = self.zipfile("Fomod.zip", {
            "fomod/info.xml": "<fomod><Name>Fomod Name</Name><Version>1.2.3</Version></fomod>",
            "fomod/ModuleConfig.xml": """
                <config>
                  <requiredInstallFiles>
                    <folder source="00 Core" destination="" />
                  </requiredInstallFiles>
                  <installSteps>
                    <installStep name="Options">
                      <optionalFileGroups>
                        <group name="Textures" type="SelectAny">
                          <plugins>
                            <plugin name="2K">
                              <typeDescriptor><type name="Required" /></typeDescriptor>
                              <files><folder source="10 2K/textures" destination="textures" /></files>
                            </plugin>
                          </plugins>
                        </group>
                      </optionalFileGroups>
                    </installStep>
                  </installSteps>
                </config>
            """,
            "00 Core/Fomod.esp": "",
            "10 2K/textures/example.dds": "dds",
        })

        inspected = mo2ctl.inspect_source(archive)
        self.assertEqual(inspected["fomod"]["default_choices"]["status"], "ready")
        result = mo2ctl.cmd_install(self.env, self.args(archive))

        dest = self.root / "mods" / "Fomod Name"
        self.assertEqual(result["installed"], "Fomod Name")
        self.assertTrue((dest / "Fomod.esp").is_file())
        self.assertTrue((dest / "textures" / "example.dds").is_file())
        self.assertEqual(
            json.loads((dest / "mo2ctl-fomod-choices.json").read_text(encoding="utf-8"))["status"],
            "ready",
        )
        self.assertIn("version=1.2.3", (dest / "meta.ini").read_text(encoding="utf-8"))

    def test_zip_slip_is_rejected(self) -> None:
        archive = self.zipfile("Bad.zip", {"../evil.esp": ""})

        with self.assertRaisesRegex(mo2ctl.Fail, "unsafe archive path"):
            mo2ctl.inspect_source(archive)

    def test_absolute_archive_path_is_rejected(self) -> None:
        archive = self.zipfile("Absolute.zip", {"/evil.esp": ""})

        with self.assertRaisesRegex(mo2ctl.Fail, "unsafe archive path"):
            mo2ctl.inspect_source(archive)

    def test_fomod_root_wins_over_data_child(self) -> None:
        archive = self.zipfile("FomodData.zip", {
            "fomod/ModuleConfig.xml": "<config />",
            "Data/ShouldNotHideFomod.esp": "",
        })

        inspected = mo2ctl.inspect_source(archive)

        self.assertTrue(inspected["has_fomod"])

    def test_unsupported_conditional_fomod_handoffs(self) -> None:
        archive = self.zipfile("Conditional.zip", {
            "fomod/ModuleConfig.xml": """
                <config>
                  <conditionalFileInstalls>
                    <patterns><pattern><dependencies /></pattern></patterns>
                  </conditionalFileInstalls>
                </config>
            """,
        })

        with self.assertRaisesRegex(mo2ctl.Fail, "handoff_user"):
            mo2ctl.cmd_install(self.env, self.args(archive))

    def test_at_least_one_without_default_handoffs(self) -> None:
        archive = self.zipfile("PickOne.zip", {
            "fomod/ModuleConfig.xml": """
                <config>
                  <installSteps>
                    <installStep name="Files">
                      <optionalFileGroups>
                        <group name="Plugin" type="SelectAtLeastOne">
                          <plugins>
                            <plugin name="DLL"><files><folder source="SKSE" destination="SKSE" /></files></plugin>
                          </plugins>
                        </group>
                      </optionalFileGroups>
                    </installStep>
                  </installSteps>
                </config>
            """,
            "SKSE/Plugins/example.dll": "",
        })

        inspected = mo2ctl.inspect_source(archive)

        self.assertEqual(inspected["fomod"]["default_choices"]["status"], "handoff_user")
        self.assertIn("SelectAtLeastOne", inspected["fomod"]["default_choices"]["handoff_reasons"][0])

    def test_uninstall_removes_manifest_entry(self) -> None:
        archive = self.zipfile("RemoveMe.zip", {"Data/RemoveMe.esp": ""})
        mo2ctl.cmd_install(self.env, self.args(archive, name="RemoveMe"))

        result = mo2ctl.cmd_uninstall(
            self.env,
            argparse.Namespace(name="RemoveMe", keep_files=False, keep_manifest=False, force=False),
        )

        self.assertTrue(result["removed_manifest"])
        manifest = json.loads((self.root / "profiles" / "manifest.json").read_text(encoding="utf-8"))
        self.assertNotIn("RemoveMe", manifest["mods"])


class Mo2CtlProfileGitTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name) / "mo2"
        self.profile = self.root / "profiles" / "QA"
        (self.root / "mods").mkdir(parents=True)
        self.profile.mkdir(parents=True)
        (self.profile / "modlist.txt").write_bytes(b"# This file was automatically generated by Mod Organizer.\r\n+Core Mod\r\n")
        (self.profile / "plugins.txt").write_text("# This file was automatically generated by Mod Organizer.\n", encoding="utf-8")
        (self.profile / "loadorder.txt").write_bytes(b"# This file was automatically generated by Mod Organizer.\r\n")
        (self.profile / "archives.txt").write_bytes(b"Skyrim - Misc.bsa\r\n")
        (self.root / "ModOrganizer.ini").write_bytes(
            b"[General]\r\nselected_profile=@ByteArray(Default)\r\nother=true\r\n"
        )
        (self.root / "profiles" / ".gitattributes").write_text("* -text\n", encoding="utf-8")
        self.env = mo2ctl.Env(self.root, "QA")
        self._lock = mo2ctl.profile_lock_reason
        mo2ctl.profile_lock_reason = lambda: None
        self.git("init", "-b", "main")
        self.git("config", "user.email", "test@example.invalid")
        self.git("config", "user.name", "Test")
        self.git("add", ".")
        self.git("commit", "-m", "baseline")

    def tearDown(self) -> None:
        mo2ctl.profile_lock_reason = self._lock
        self.tmp.cleanup()

    def git(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args],
            cwd=self.root / "profiles",
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )

    def args(self, **overrides) -> argparse.Namespace:
        data = {"force": False}
        data.update(overrides)
        return argparse.Namespace(**data)

    def zipfile(self, name: str, entries: dict[str, str]) -> Path:
        path = Path(self.tmp.name) / name
        with zipfile.ZipFile(path, "w") as zf:
            for member, text in entries.items():
                zf.writestr(member, text)
        return path

    def install_args(self, source: Path, **overrides) -> argparse.Namespace:
        data = {
            "source": str(source),
            "name": overrides.pop("name", None),
            "no_enable": False,
            "force": False,
            "priority": "bottom",
            "fomod_choices": None,
            "version": "0.0.0",
            "source_url": None,
            "no_manifest": False,
            "comment": "test",
        }
        data.update(overrides)
        return argparse.Namespace(**data)

    def test_try_fail_removes_added_mod_and_restores_main(self) -> None:
        mo2ctl.cmd_try_begin(self.env, self.args(name="New Mod", branch=None))
        archive = self.zipfile("NewMod.zip", {"Data/NewMod.esp": ""})
        mo2ctl.cmd_install(self.env, self.install_args(archive, name="New Mod"))

        result = mo2ctl.cmd_try_fail(self.env, self.args(uninstall=[], force=False))

        self.assertEqual(result["checked_out"], "main")
        self.assertFalse((self.root / "mods" / "New Mod").exists())
        self.assertNotIn(b"New Mod", (self.profile / "modlist.txt").read_bytes())
        self.assertEqual(self.git("branch", "--show-current").stdout.strip(), "main")
        self.assertEqual(self.git("status", "--porcelain").stdout, "")

    def test_try_pass_commits_and_fast_forwards_main(self) -> None:
        mo2ctl.cmd_try_begin(self.env, self.args(name="Merge Me", branch=None))
        archive = self.zipfile("MergeMe.zip", {"Data/MergeMe.esp": ""})
        mo2ctl.cmd_install(self.env, self.install_args(archive, name="Merge Me"))

        result = mo2ctl.cmd_try_pass(
            self.env,
            self.args(message="Validate Merge Me", delete_branch=True, force=False),
        )

        self.assertEqual(result["checked_out"], "main")
        self.assertIsNotNone(result["committed"])
        self.assertIn(b"Merge Me", (self.profile / "modlist.txt").read_bytes())
        self.assertIn("Merge Me", json.loads((self.root / "profiles" / "manifest.json").read_text(encoding="utf-8"))["mods"])
        self.assertEqual(self.git("status", "--porcelain").stdout, "")

    def test_semantics_ignore_known_engine_churn(self) -> None:
        (self.profile / "plugins.txt").write_text(
            "# This file was automatically generated by Mod Organizer 2.\n",
            encoding="utf-8",
        )
        (self.profile / "loadorder.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n"
            b"ccbgssse068-bloodfall.esl\r\n"
            b"ccbgssse069-contest.esl\r\n"
            b"ccvsvsse004-beafarmer.esl\r\n"
        )

        result = mo2ctl.cmd_profile_semantics(self.env, argparse.Namespace(ref="HEAD", show=False))

        self.assertTrue(result["equivalent"])
        self.assertEqual(result["diff"], {})

    def test_try_begin_absorbs_known_engine_churn_before_branching(self) -> None:
        (self.profile / "plugins.txt").write_text(
            "# This file was automatically generated by Mod Organizer 2.\n",
            encoding="utf-8",
        )
        (self.profile / "loadorder.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n"
            b"ccbgssse068-bloodfall.esl\r\n"
        )

        result = mo2ctl.cmd_try_begin(self.env, self.args(name="Churn", branch=None, absorb_message=None))

        self.assertTrue(result["absorbed_churn"]["absorbed"])
        self.assertEqual(self.git("status", "--porcelain").stdout, "")
        self.assertEqual(self.git("branch", "--show-current").stdout.strip(), "try/churn")

    def test_absorb_churn_rejects_semantic_changes(self) -> None:
        (self.profile / "modlist.txt").write_bytes(
            b"# This file was automatically generated by Mod Organizer.\r\n+Core Mod\r\n+Real Mod\r\n"
        )

        with self.assertRaisesRegex(mo2ctl.Fail, "non-churn changes"):
            mo2ctl.cmd_profile_absorb_churn(self.env, self.args(message=None, force=False))

    def test_select_profile_preserves_crlf_and_requires_one_hit(self) -> None:
        result = mo2ctl.cmd_select_profile(self.env, self.args(profile="QA", force=False))

        raw = (self.root / "ModOrganizer.ini").read_bytes()
        self.assertEqual(result["eol"], "CRLF")
        self.assertIn(b"selected_profile=@ByteArray(QA)\r\n", raw)
        self.assertEqual(raw.count(b"selected_profile="), 1)


class Mo2CtlBackgroundActiveTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name) / "mo2"
        self.profile = self.root / "profiles" / "QA"
        self.profile.mkdir(parents=True)
        self.env = mo2ctl.Env(self.root, "QA")

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def write_ini(self, data: bytes) -> None:
        (self.profile / "skyrim.ini").write_bytes(data)

    def test_enable_and_restore_preserve_exact_original_bytes(self) -> None:
        original = b"[General]\r\nsLanguage=ENGLISH\r\n[Display]\r\nbAllowScreenshot=1\r\n"
        self.write_ini(original)

        enabled = mo2ctl.enable_background_active(self.env)

        self.assertTrue(enabled["enabled"])
        active = (self.profile / "skyrim.ini").read_bytes()
        self.assertIn(b"[General]\r\nbAlwaysActive=1\r\n", active)
        self.assertNotIn(b"\n", active.replace(b"\r\n", b""))
        restored = mo2ctl.restore_background_active(self.env)
        self.assertTrue(restored["restored"])
        self.assertEqual((self.profile / "skyrim.ini").read_bytes(), original)
        self.assertFalse(mo2ctl.background_active_backup(self.env).exists())

    def test_existing_setting_is_temporarily_overridden(self) -> None:
        original = b"[General]\nbAlwaysActive=0\nsLanguage=ENGLISH\n"
        self.write_ini(original)

        mo2ctl.enable_background_active(self.env)

        self.assertEqual(
            (self.profile / "skyrim.ini").read_bytes(),
            b"[General]\nbAlwaysActive=1\nsLanguage=ENGLISH\n",
        )
        mo2ctl.restore_background_active(self.env)
        self.assertEqual((self.profile / "skyrim.ini").read_bytes(), original)

    def test_missing_general_section_is_created_temporarily(self) -> None:
        original = b"[Display]\nbAllowScreenshot=1\n"
        self.write_ini(original)

        mo2ctl.enable_background_active(self.env)

        self.assertTrue(
            (self.profile / "skyrim.ini").read_bytes().startswith(
                b"[General]\nbAlwaysActive=1\n[Display]\n"
            )
        )
        mo2ctl.restore_background_active(self.env)
        self.assertEqual((self.profile / "skyrim.ini").read_bytes(), original)

    def test_stale_backup_is_recovered_before_next_enable(self) -> None:
        first = b"[General]\nbAlwaysActive=0\n"
        self.write_ini(first)
        mo2ctl.enable_background_active(self.env)
        (self.profile / "skyrim.ini").write_bytes(b"corrupt interrupted run\n")

        mo2ctl.enable_background_active(self.env)
        mo2ctl.restore_background_active(self.env)

        self.assertEqual((self.profile / "skyrim.ini").read_bytes(), first)

    @patch("mo2ctl.game_pids", return_value=[])
    def test_kill_restores_even_when_process_already_exited(self, _game_pids) -> None:
        original = b"[General]\nbAlwaysActive=0\n"
        self.write_ini(original)
        mo2ctl.enable_background_active(self.env)

        result = mo2ctl.cmd_kill(
            self.env, argparse.Namespace(mo2=False, timeout=0),
        )

        self.assertTrue(result["background_active"]["restored"])
        self.assertEqual((self.profile / "skyrim.ini").read_bytes(), original)

    @patch("mo2ctl.mo2_pids", return_value=[])
    @patch("mo2ctl.game_pids", return_value=[])
    @patch("mo2ctl.subprocess.Popen", side_effect=OSError("spawn failed"))
    def test_launch_spawn_failure_restores_original(
        self, _popen, _game_pids, _mo2_pids,
    ) -> None:
        original = b"[General]\nbAlwaysActive=0\n"
        self.write_ini(original)
        args = argparse.Namespace(
            shortcut="SKSE", wait=1, no_wait=False, background_active=True,
        )

        with self.assertRaisesRegex(OSError, "spawn failed"):
            mo2ctl.cmd_launch(self.env, args)

        self.assertEqual((self.profile / "skyrim.ini").read_bytes(), original)
        self.assertFalse(mo2ctl.background_active_backup(self.env).exists())


class Mo2CtlStaticGateTests(unittest.TestCase):
    def result(self, tool: str, text: str, **arguments) -> dict:
        return {"tool": tool, "arguments": arguments, "is_error": False, "text": text}

    def capture(self, *tools: dict) -> dict:
        return {
            "format": mo2ctl.STATIC_GATE_FORMAT,
            "profile": "QA",
            "tools": list(tools),
            "crash_logs": {"checked": False},
        }

    def test_load_order_gate_ignores_known_cc_churn_warnings(self) -> None:
        capture = self.capture(self.result(
            "housecarl_load_order_status",
            "warnings (3):\n"
            "  - load order lists 'ccbgssse068-bloodfall.esl' but no enabled mod provides it.\n"
            "  - load order lists 'ccbgssse069-contest.esl' but no enabled mod provides it.\n"
            "  - load order lists 'ccvsvsse004-beafarmer.esl' but no enabled mod provides it.\n",
        ))

        evaluated = mo2ctl.evaluate_static_gates(capture)

        self.assertEqual(evaluated["status"], "pass")

    def test_skse_gate_fails_only_on_new_diagnostics_against_baseline(self) -> None:
        base = self.capture(self.result(
            "housecarl_skse_inventory",
            "contested DLL: BehaviorDataInjector.dll\n",
        ))
        current = self.capture(self.result(
            "housecarl_skse_inventory",
            "contested DLL: BehaviorDataInjector.dll\n"
            "contested DLL: PapyrusUtil.dll\n",
        ))

        evaluated = mo2ctl.evaluate_static_gates(current, base)

        self.assertEqual(evaluated["status"], "fail")
        self.assertIn("PapyrusUtil.dll", evaluated["gates"][0]["findings"][0])

    def test_skse_gate_ignores_aggregate_count_change_when_diagnostics_match(self) -> None:
        locked = (
            "[!] version-LOCKED plugins (1) — load ONLY on their listed runtime(s):\n"
            "  - Existing.dll → 1.6.1170\n\n"
            "contested DLLs (shipped by >1 mod — winner-first conflict chain):\n"
            "  - ExistingConflict.dll: Winner (loose) › Loser (loose)\n"
        )
        base = self.capture(self.result(
            "housecarl_skse_inventory",
            "compat: 72 Address Library · 0 signature-scanning · 1 version-LOCKED\n\n"
            + locked,
        ))
        current = self.capture(self.result(
            "housecarl_skse_inventory",
            "compat: 73 Address Library · 0 signature-scanning · 1 version-LOCKED\n\n"
            + locked,
        ))

        evaluated = mo2ctl.evaluate_static_gates(current, base)

        self.assertEqual(evaluated["status"], "pass")

    def test_skse_gate_fails_on_new_locked_plugin_item(self) -> None:
        base = self.capture(self.result(
            "housecarl_skse_inventory",
            "[!] version-LOCKED plugins (1) — details:\n"
            "  - Existing.dll → 1.6.1170\n",
        ))
        current = self.capture(self.result(
            "housecarl_skse_inventory",
            "[!] version-LOCKED plugins (2) — details:\n"
            "  - Existing.dll → 1.6.1170\n"
            "  - NewRisk.dll → 1.6.640\n",
        ))

        evaluated = mo2ctl.evaluate_static_gates(current, base)

        self.assertEqual(evaluated["status"], "fail")
        self.assertEqual(
            evaluated["gates"][0]["findings"],
            ["version-locked: NewRisk.dll → 1.6.640"],
        )

    def test_skse_gate_fails_closed_on_capped_diagnostic_section(self) -> None:
        truncated = self.capture(self.result(
            "housecarl_skse_inventory",
            "[!] version-LOCKED plugins (2) — details:\n"
            "  - Existing.dll → 1.6.1170\n"
            "  ... [showing 1 of 2; raise max_chars or use filter= to see all]\n",
        ))

        evaluated = mo2ctl.evaluate_static_gates(truncated, truncated)

        self.assertEqual(evaluated["status"], "fail")
        self.assertTrue(any(
            "SKSE diagnostic inventory incomplete" in finding
            for finding in evaluated["gates"][0]["findings"]
        ))

    def test_check_errors_missing_master_increase_fails(self) -> None:
        base = self.capture(self.result(
            "housecarl_check_errors",
            "scanned 1 plugins · 0 dangling ref(s) · 0 missing master(s)\n",
        ))
        current = self.capture(self.result(
            "housecarl_check_errors",
            "scanned 1 plugins · 0 dangling ref(s) · 1 missing master(s)\n",
        ))

        evaluated = mo2ctl.evaluate_static_gates(current, base)

        self.assertEqual(evaluated["status"], "fail")
        self.assertEqual(evaluated["gates"][0]["findings"], ["missing masters increased: 0 -> 1"])

    def test_scoped_validate_scripts_zero_counts_passes(self) -> None:
        current = self.capture(self.result(
            "housecarl_validate_scripts",
            "validate_scripts — VMAD script-property binding sweep\n"
            "scanned 1 plugin · 0 record(s) with scripts · 0 unbound · "
            "0 bound-but-null · 0 unverifiable\n\n"
            "No unbound script properties found in the scanned scope.\n",
            plugins=["BendTimeRings.esp"],
        ))

        evaluated = mo2ctl.evaluate_static_gates(current)

        self.assertEqual(evaluated["status"], "pass")

    def test_crash_logs_use_local_filename_time_and_dedupe_one_second(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            folder = Path(tmp)
            first = folder / "crash-2026-08-06-10-00-00.log"
            duplicate = folder / "crash-2026-08-06-10-00-01.log"
            later = folder / "crash-2026-08-06-10-02-00.log"
            first.write_text("Unhandled exception\nUptime: 6599\nAgentBridge.dll+0054404\n", encoding="utf-8")
            duplicate.write_text("partial handler crash\n", encoding="utf-8")
            later.write_text("CALL STACK\nSkyrimSE.exe+02C3957\n", encoding="utf-8")
            args = argparse.Namespace(crash_since="2026-08-06T01:59:00Z", mod="AgentBridge")
            status = self.result(
                "housecarl_load_order_status",
                f"crash_logs: {folder}  (configured)\n",
            )

            local_tz = timezone(timedelta(hours=8))
            result = mo2ctl.crash_triage_from_capture([status], args, local_tz)

            self.assertTrue(result["checked"])
            self.assertEqual(len(result["new_logs"]), 2)
            self.assertEqual(result["new_logs"][0]["time"], "2026-08-06T02:00:00+00:00")
            self.assertFalse(result["new_logs"][0]["has_call_stack"])
            self.assertEqual(result["new_logs"][0]["uptime_bin"], "load/plugin-conflict window")
            self.assertEqual(result["new_logs"][0]["attribution"], "candidate")

    def test_crash_since_utc_excludes_older_local_timestamp(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            folder = Path(tmp)
            older = folder / "crash-2026-08-06-10-00-00.log"
            newer = folder / "crash-2026-08-06-10-02-00.log"
            older.write_text("older\n", encoding="utf-8")
            newer.write_text("newer\n", encoding="utf-8")
            args = argparse.Namespace(crash_since="2026-08-06T02:01:00Z", mod=None)
            status = self.result(
                "housecarl_load_order_status",
                f"crash_logs: {folder}  (configured)\n",
            )

            result = mo2ctl.crash_triage_from_capture(
                [status], args, timezone(timedelta(hours=8))
            )

            self.assertEqual([Path(item["file"]).name for item in result["new_logs"]], [newer.name])
            self.assertEqual(result["new_logs"][0]["time"], "2026-08-06T02:02:00+00:00")


if __name__ == "__main__":
    unittest.main()
